name: Build Packer Custom Image

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Create artifact application
        run: zip -r webapp.zip ./*  # Adjust this if you want to zip a specific directory

      - name: Verify zip content
        run: unzip -l webapp.zip

      - name: Upload application artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp-artifact
          path: webapp.zip  # Path to the zip file created

  build_ami:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Adjust as needed

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp-artifact
          path: ./  # Ensure this is correctly indented

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Initialize Packer
        run: |
          packer init aws.pkr.hcl

      - name: Build Packer Image
        run: |
          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "aws_source_ami=${{ secrets.AWS_SOURCE_AMI }}" \
            -var "instance_type=${{ secrets.INSTANCE_TYPE }}" \
            -var "ssh_username=${{ secrets.SSH_USERNAME }}" \
            -var "ami_name=${{ secrets.AMI_NAME }}" \
            -var "volume_size=${{ secrets.VOLUME_SIZE }}" \
            -var "volume_type=${{ secrets.VOLUME_TYPE }}" \
            -var "demo_account_id=${{secrets.DEMO_ACCOUNT_ID}}" \
            aws.pkr.hcl
