name: Packer PR Status Check

on:
  pull_request:
    branches:
      - main  # Adjust as needed

jobs:
  format-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        run: |
          curl -LO https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer version

      - name: Initialize Packer
        run: packer init aws.pkr.hcl

      - name: Run packer fmt
        id: fmt
        run: |
          packer fmt
          if [[ $(git status --porcelain) ]]; then
            echo "Packer templates are not formatted correctly."
            exit 1
          fi

      - name: Run packer validate
        run: packer validate aws.pkr.hcl
