name: Packer Validate on PR

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip zip
        wget https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_amd64.zip
        unzip packer_1.11.2_linux_amd64.zip
        sudo mv packer /usr/local/bin/
        rm packer_1.11.2_linux_amd64.zip

    - name: List files in the repository
      run: ls -al

    - name: Print current working directory
      run: pwd

    - name: Create webapp.zip artifact
      run: |
        echo "Attempting to zip files..."
        zip -r webapp.zip ./*
        
    - name: Verify zip content
      run: zip -l webapp.zip

    - name: Initialize Packer
      run: packer init aws.pkr.hcl

    - name: Run packer fmt
      id: packer_fmt
      run: |
        packer fmt -diff -check aws.pkr.hcl
      continue-on-error: true

    - name: Fail if packer fmt modifies files
      if: steps.packer_fmt.outcome == 'failure'
      run: |
        echo "Packer fmt modified files. Please run 'packer fmt' locally and commit the changes."
        exit 1

    - name: Validate Packer template
      run: |
        packer validate aws.pkr.hcl
