name: Packer Validate on PR

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip zip
        wget https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_amd64.zip
        unzip packer_1.11.2_linux_amd64.zip
        sudo mv packer /usr/local/bin/
        rm packer_1.11.2_linux_amd64.zip

    - name: Initialize Packer
      run: packer init aws.pkr.hcl

    - name: Run packer fmt
      id: packer_fmt
      run: |
        packer fmt -diff -check aws.pkr.hcl
      continue-on-error: true

    - name: Fail if packer fmt modifies files
      if: steps.packer_fmt.outcome == 'failure'
      run: |
        echo "Packer fmt modified files. Please run 'packer fmt' locally and commit the changes."
        exit 1

    - name: Validate Packer template
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}
        
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        
      run: |
        touch test.txt
        zip webapp.zip test.txt
      
        packer validate \
            -var "aws_region=$AWS_REGION" \
            -var "aws_source_ami=$AWS_SOURCE_AMI" \
            
            -var "ssh_username=$SSH_USERNAME" \
            
            aws.pkr.hcl
